# Generated by Django 4.0 on 2021-12-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buynow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField()),
                ('category', models.TextField(blank=True, max_length=20)),
                ('food', models.CharField(blank=True, max_length=20)),
                ('adress', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'Yangi'), ('accepted', 'qabul qilingan')], default='New', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
