# Generated by Django 4.0 on 2021-12-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsingle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogsingle',
        ),
    ]
