# Generated by Django 4.0 on 2021-12-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buynow',
        ),
    ]
